// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

#ifndef __CXL_LINK_H__
#define __CXL_LINK_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* Enums for CXL Error info */
// mapped to CXL_CORRECTED_ERROR_IRQ
// CXL_TOP_CXL_CONT_GENERIC_INTERRUPT_STATUS_04[12:6]
enum cxl_corr_errors {
  CORR_CACHE_DATA_ECC = 0,
  CORR_MEM_DATA_ECC,
  CORR_CRC_THRESHOLD,
  CORR_RETRY_THRESHOLD,
  CACHE_POISON_RVD,
  MEM_POISON_RVD,
  PHY_LAYER_ERR,
  MAX_CORR_ERR_COUNT = 7
};

// mapped to CXL_UNCORRECTED_ERROR_IRQ
// CXL_CONT_GENERIC_INTERRUPT_STATUS_03[16:0]
enum cxl_uncorr_errors {
  CACHE_DATA_PAR = 0,
  CACHE_ADD_PAR,
  CACHE_BE_PAR,
  CACHE_DATA_ECC,
  MEM_DATA_PAR,
  MEM_ADD_PAR,
  MEM_BE_PAR,
  MEM_DATA_ECC,
  REINIT_THRESHOLD,
  ENCOD_VIOLATION,
  POISON_RVD,
  RCVR_OVERFLOW,
  RSVDP_12,
  RSVDP_13,
  CXL_INTERNAL_ERR,
  CXL_IDE_TX_ER,
  CXL_IDE_RX_ER,
  MAX_UNCORR_ERR_COUNT = 17
};

// mapped to 13 IRQ lines from CXL_ERR_STS_IRQ
// CXL_TOP_CXL_CONT_GENERIC_INTERRUPT_STATUS_01[28:16]
enum cxl_err_sts {
  UNCOR_INTERNAL_ERR_STS = 0,
  SURPRISE_DOWN_ER_STS,
  REPLAY_TIMER_TIMEOUT_ERR_STS,
  REPLAY_NUMBER_ROLLOVER_ERR_STS,
  RCVR_OVERFLOW_ERR_STS,
  RCVR_ERR_STS,
  MLF_TLP_ERR_STS,
  FC_PROTOCOL_ERR_STS,
  ECRC_ERR_STS,
  DL_PROTOCOL_ERR_STS,
  CORRECTED_INTERNAL_ERR_STS,
  BAD_TLP_ERR_STS,
  BAD_DLLP_ERR_STS,
  MAX_CXL_CFG_ERR_COUNT = 13
};

#ifdef __cplusplus
}
#endif

#endif /* __CXL_LINK_H__ */